env:
- DOCKER_COMPOSE_VERSION=1.23.2

# The jobs section declares jobs available in this build context
jobs:
  include:
    # lint and run tests
    - stage: "lint-and-test"
      name: "Lint, run tests"
      language: node_js
      install:
        - npm ci
      script:
        - npm run testAndLint

    - stage: publish
      name: "Run semantic-release and publish a new version"
      language: node_js
      install:
        - npm ci
        # Install a new version of the openshift cli
        - mkdir -p /opt/openshift
        - wget -qO- https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz | tar xvzf - -C /opt/openshift --strip-components=1
        - export PATH=$PATH:/opt/openshift
        - echo $OPENSHIFT_CERT | base64 --decode > /tmp/openshift.crt
      script:
        - npx semantic-release

    - stage: e2e
      services:
        - docker
      before_install:
        # Install a newer version of docker-compose than the one provided by Travis
        - sudo rm /usr/local/bin/docker-compose
        - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
        - chmod +x docker-compose
        - sudo mv docker-compose /usr/local/bin
        - sudo apt-get install libgconf-2-4 # cypress needs this
      install:
        - npm ci
      script:
        - npm run testAndLint

# Flow control
# This section defines the order in which stages are run and when to run certain stages
stages:
  - name: lint-and-test
    if: branch != master AND tag IS NOT present
  - name: publish
    if: (branch = master AND type != pull_request)
  - name: e2e
    if: type = pull_request

notifications:
  email:
    on_success: never
    on_failure: change
